### PR TITLE
faster and safer numberToString

### PR DESCRIPTION
**Pull request by tramchamploo**

### CODE REVIEW

**Comment by stephenmcd** [comment]
Awesome, thank you!

You've got a dozen other (seemingly empty) commits in this PR - is it possible to clean that up? Perhaps fork the repo again?

With that out of the way, go ahead and add your name to the AUTHORS file too (might as well do that in the same commit).

**Comment by stephenmcd** [comment]
Also would you mind describing the benefit?

**Comment by stephenmcd** [comment]
I guess I'm keen to know how much faster and why is it safer - there are some concepts not used in the project here, just wondering if it's worth introducing those if the benefit isn't great.

**Comment by tramchamploo** [comment]
It's just type safer.Wrote a test myself it's a bit faster maybe because it's not comparing strings

**Comment by stephenmcd** [comment]
How about something like `if (number.floor == number)`

**Comment by tramchamploo** [comment]
Numeric doesn't have a floor method

**Pull request closed without merging**
